name: E2E Test

on:
  push:
    branches:
      - "**"

jobs:
  test-e2e:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      - uses: actions/setup-go@v2.2.0
        with:
          go-version: 1.18
      - uses: actions/checkout@v2
      - uses: technote-space/get-diff-action@v6.0.1
        with:
          PATTERNS: |
            **/**.go
            go.mod
            go.sum
      - name: Build Docker Image
        run: |
          make docker-build-debug
        if: env.GIT_DIFF
      - name: Test E2E
        run: |
          make test-e2e-skip-upgrade
        if: env.GIT_DIFF
  